name: Continous Integration

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run Tests
        run: yarn coverage
        env:
          VITE_HYPIXEL_API_KEY: ${{ secrets.VITE_HYPIXEL_API_KEY }}
          VITE_TESTING_USERNAME: ${{ vars.VITE_TESTING_USERNAME }}
          VITE_TESTING_UUID: ${{ vars.VITE_TESTING_USER_UUID }}

      - name: Build
        run: yarn build
